template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 12
template_sha = "eed18c5e13f1abb79cc614c725cc05d1763efd66"

[replacements]
__UND2C__ = "hdn"
__UNDEFINED__ = "Northern Haida"
__UND__ = "hdn"
__LICENSE__ = "LGPLv3"
